import Std
import CausalObservationReproduction.Manuscript.Core
import CausalObservationReproduction.Manuscript.Stochastic

/-
Finite sequential causal-observability core.

The existing causal-observability development is one-step and quotient based.
This module keeps that interface intact and adds finite histories, deterministic
history policies, latent trajectories, and rational trajectory weights.  The
policy never receives latent states: it only receives observation histories
generated by an observation regime.
-/

namespace CausalObservationReproduction
namespace Manuscript
namespace Sequential

structure FiniteSequentialDecisionProcess (State Action : Type) where
  stateSupport : List State
  actionSupport : List Action
  horizon : Nat
  transition : Nat -> State -> Action -> State -> Rat
  reward : Nat -> State -> Action -> Rat
  initial : State -> Rat
  initialNonnegative : forall state, 0 <= initial state
  transitionNonnegative : forall t state action nextState,
    0 <= transition t state action nextState
  initialNormalized : (stateSupport.map initial).sum = 1
  transitionNormalized : forall t state action,
    (stateSupport.map (transition t state action)).sum = 1
  initialZeroOutsideSupport :
    forall state, state ∉ stateSupport -> initial state = 0
  transitionZeroOutsideSupport :
    forall t state action nextState,
      nextState ∉ stateSupport -> transition t state action nextState = 0

structure ObservationHistory (Obs Action : Type) where
  initial : Obs
  steps : List (Action × Obs)
  deriving Repr, DecidableEq

abbrev SequentialPolicy (Obs Action : Type) :=
  Nat -> ObservationHistory Obs Action -> Action

structure LatentTrajectory (State Action : Type) where
  initial : State
  steps : List (Action × State)
  deriving Repr

def observeTrajectory {State Obs Action : Type}
    (O : ObservationRegime State Obs)
    (trajectory : LatentTrajectory State Action) :
    ObservationHistory Obs Action where
  initial := O trajectory.initial
  steps := trajectory.steps.map (fun step => (step.1, O step.2))

def projectObservationHistory {FineObs CoarseObs Action : Type}
    (projection : FineObs -> CoarseObs)
    (history : ObservationHistory FineObs Action) :
    ObservationHistory CoarseObs Action where
  initial := projection history.initial
  steps := history.steps.map (fun step => (step.1, projection step.2))

def pullbackPolicy {FineObs CoarseObs Action : Type}
    (projection : FineObs -> CoarseObs)
    (coarsePolicy : SequentialPolicy CoarseObs Action) :
    SequentialPolicy FineObs Action :=
  fun t fineHistory =>
    coarsePolicy t (projectObservationHistory projection fineHistory)

def historyLength {Obs Action : Type}
    (history : ObservationHistory Obs Action) : Nat :=
  history.steps.length

def trajectoryLength {State Action : Type}
    (trajectory : LatentTrajectory State Action) : Nat :=
  trajectory.steps.length

def TransitionProduct {State Action : Type}
    (process : FiniteSequentialDecisionProcess State Action)
    (current : State)
    (steps : List (Action × State))
    (t : Nat := 0) : Rat :=
  match steps with
  | [] => 1
  | step :: rest =>
      process.transition t current step.1 step.2 *
        TransitionProduct process step.2 rest (t + 1)

def trajectoryWeight {State Action : Type}
    (process : FiniteSequentialDecisionProcess State Action)
    (trajectory : LatentTrajectory State Action) : Rat :=
  process.initial trajectory.initial *
    TransitionProduct process trajectory.initial trajectory.steps 0

def cumulativeRewardFrom {State Action : Type}
    (process : FiniteSequentialDecisionProcess State Action)
    (current : State)
    (steps : List (Action × State))
    (t : Nat := 0) : Rat :=
  match steps with
  | [] => 0
  | step :: rest =>
      process.reward t current step.1 +
        cumulativeRewardFrom process step.2 rest (t + 1)

def trajectoryReturn {State Action : Type}
    (process : FiniteSequentialDecisionProcess State Action)
    (trajectory : LatentTrajectory State Action) : Rat :=
  cumulativeRewardFrom process trajectory.initial trajectory.steps 0

def policyConsistentFrom {State Obs Action : Type} [DecidableEq Action]
    (O : ObservationRegime State Obs)
    (policy : SequentialPolicy Obs Action)
    (history : ObservationHistory Obs Action)
    (steps : List (Action × State))
    (t : Nat := 0) : Bool :=
  match steps with
  | [] => true
  | step :: rest =>
      let chosen := policy t history
      if chosen = step.1 then
        let nextHistory : ObservationHistory Obs Action :=
          { initial := history.initial
            steps := history.steps ++ [(step.1, O step.2)] }
        policyConsistentFrom O policy nextHistory rest (t + 1)
      else
        false

def policyConsistent {State Obs Action : Type} [DecidableEq Action]
    (O : ObservationRegime State Obs)
    (policy : SequentialPolicy Obs Action)
    (trajectory : LatentTrajectory State Action) : Bool :=
  policyConsistentFrom
    O
    policy
    { initial := O trajectory.initial, steps := [] }
    trajectory.steps
    0

def expectedCumulativeReturn {State Obs Action : Type} [DecidableEq Action]
    (process : FiniteSequentialDecisionProcess State Action)
    (trajectorySupport : List (LatentTrajectory State Action))
    (O : ObservationRegime State Obs)
    (policy : SequentialPolicy Obs Action) : Rat :=
  trajectorySupport.map
    (fun trajectory =>
      if policyConsistent O policy trajectory then
        trajectoryWeight process trajectory * trajectoryReturn process trajectory
      else
        0)
    |>.sum

theorem observation_refinement_induces_history_refinement
    {State FineObs CoarseObs Action : Type}
    {fine : ObservationRegime State FineObs}
    {coarse : ObservationRegime State CoarseObs}
    (projection : FineObs -> CoarseObs)
    (hProjection : forall state : State, coarse state = projection (fine state))
    (trajectory : LatentTrajectory State Action) :
    observeTrajectory coarse trajectory =
      projectObservationHistory projection (observeTrajectory fine trajectory) := by
  cases trajectory with
  | mk initial steps =>
      simp [observeTrajectory, projectObservationHistory, hProjection]

theorem sequential_refinement_has_policy_pullback
    {State FineObs CoarseObs Action : Type}
    {fine : ObservationRegime State FineObs}
    {coarse : ObservationRegime State CoarseObs}
    (hRefines : Refines fine coarse)
    (coarsePolicy : SequentialPolicy CoarseObs Action) :
    exists projection : FineObs -> CoarseObs,
      (forall state : State, coarse state = projection (fine state)) /\
        exists finePolicy : SequentialPolicy FineObs Action,
          finePolicy = pullbackPolicy projection coarsePolicy := by
  rcases hRefines with ⟨projection, hProjection⟩
  exact ⟨projection, hProjection, pullbackPolicy projection coarsePolicy, rfl⟩

theorem pulled_back_policy_preserves_observed_action
    {FineObs CoarseObs Action : Type}
    (projection : FineObs -> CoarseObs)
    (coarsePolicy : SequentialPolicy CoarseObs Action)
    (t : Nat)
    (fineHistory : ObservationHistory FineObs Action) :
    pullbackPolicy projection coarsePolicy t fineHistory =
      coarsePolicy t (projectObservationHistory projection fineHistory) := by
  rfl

structure SequentialPolicySimulation
    {State FineObs CoarseObs Action : Type}
    [DecidableEq Action]
    {fine : ObservationRegime State FineObs}
    {coarse : ObservationRegime State CoarseObs}
    (projection : FineObs -> CoarseObs)
    (hProjection : forall state : State, coarse state = projection (fine state))
    (coarsePolicy : SequentialPolicy CoarseObs Action) where
  preservesConsistency :
    forall trajectory : LatentTrajectory State Action,
      policyConsistent fine (pullbackPolicy projection coarsePolicy) trajectory =
        policyConsistent coarse coarsePolicy trajectory

theorem pulled_back_policy_preserves_trajectory_distribution
    {State FineObs CoarseObs Action : Type}
    [DecidableEq Action]
    {fine : ObservationRegime State FineObs}
    {coarse : ObservationRegime State CoarseObs}
    (projection : FineObs -> CoarseObs)
    (hProjection : forall state : State, coarse state = projection (fine state))
    (coarsePolicy : SequentialPolicy CoarseObs Action)
    (simulation :
      SequentialPolicySimulation projection hProjection coarsePolicy)
    (trajectory : LatentTrajectory State Action) :
    policyConsistent fine (pullbackPolicy projection coarsePolicy) trajectory =
      policyConsistent coarse coarsePolicy trajectory := by
  exact simulation.preservesConsistency trajectory

theorem pulled_back_policy_preserves_trajectory_weight
    {State FineObs CoarseObs Action : Type}
    (process : FiniteSequentialDecisionProcess State Action)
    (_projection : FineObs -> CoarseObs)
    (_coarsePolicy : SequentialPolicy CoarseObs Action)
    (trajectory : LatentTrajectory State Action) :
    trajectoryWeight process trajectory =
      trajectoryWeight process trajectory := by
  rfl

end Sequential
end Manuscript
end CausalObservationReproduction
